<?php

namespace APA\SecurityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUser($search)
    {
       if (count($search) > 1)
       {
            $qb = $this->createQueryBuilder('c')->where('c.nom = :search')->andWhere('c.prenom = :search1')
                                                ->orWhere('c.nom = :search1')->orWhere('c.prenom = :search')
                                                ->setParameters(array('search' => $search[0] , 'search1' => $search[1]))->getQuery()->getResult();
       }
       else 
       {      
          $qb = $this->createQueryBuilder('c')->where('c.nom = :search')->orWhere('c.prenom = :search')
                                              ->setParameters(array('search' => $search))->getQuery()->getResult();
       }
        
       return $qb;

    }
}
