security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      12

    role_hierarchy:
        ROLE_ADMIN:        ROLE_PATIENT

    providers:
        in_memory:
            memory:
                users:
                    patient:
                        password: $2y$12$kCd9kPssA2o8gHYSEUERnOgPgW9ctagElI0hYdRfkiLOwLrCn8OaW
                        roles: [ 'ROLE_PATIENT' ]
                    admin:
                        password: $2y$12$UP.HnDMSwv2qW0FcFw5RQOwIRGyQoPzyPoeIIO/1LXMZUX0dIzXty
                        roles: [ 'ROLE_ADMIN' ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login$
            anonymous: true
        main:
            pattern:   ^/
            anonymous: false
            provider: in_memory
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /login

    access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
