security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      12
        APA\SecurityBundle\Entity\User:
            algorithm: bcrypt
            cost:      12

#    role_hierarchy:
#        ROLE_ADMIN: ROLE_USER

    providers:
        main:
            entity:
                class: APA\SecurityBundle\Entity\User
                property: username
        in_memory:
            memory:
                users:
                    user:
                        password: $2y$12$kCd9kPssA2o8gHYSEUERnOgPgW9ctagElI0hYdRfkiLOwLrCn8OaW
                        roles: [ 'ROLE_USER' ]
                    admin:
                        password: $2y$12$UP.HnDMSwv2qW0FcFw5RQOwIRGyQoPzyPoeIIO/1LXMZUX0dIzXty
                        roles: [ 'ROLE_ADMIN' ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # Login is only used for the /login page. It allows anonymous users.
        login:
            pattern: ^/login$
            anonymous: true
        # main is used for every page besides /login. It redirects anonymous users to /login.
        main:
            pattern:   ^/
            anonymous: false
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /login

    access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
