apa_message_inbox:
    path:     /Message/inbox
    defaults:
        _controller: APAMessageBundle:Message:inbox

apa_message_sendMessage:
    path:     /Message/send/{id}
    defaults:
        _controller: APAMessageBundle:Message:sendMessage
    requirements:
        id: \d+
