apa_platform_index:
    path:     /
    defaults:
        _controller: APAPlatformBundle:Default:index

apa_platform_adminIndex:
    path: /admin
    defaults:
        _controller: APAPlatformBundle:Default:adminIndex

apa_platform_addUser:
    path: /admin/addUser
    defaults:
        _controller: APAPlatformBundle:Default:addUser

apa_platform_deleteUser:
    path: /admin/delete/{id}
    defaults:
        _controller: APAPlatformBundle:Default:deleteUser
    requirements:
        id: \d+
