# PARTIE ADMIN

apa_platform_adminIndex:
    path: /admin
    defaults:
        _controller: APAPlatformBundle:Admin:adminIndex

apa_platform_adminListe:
    path: /admin/liste
    defaults:
        _controller: APAPlatformBundle:Admin:adminListe

apa_platform_addUser:
    path: /admin/addUser
    defaults:
        _controller: APAPlatformBundle:Admin:addUser

apa_platform_deleteUser:
    path: /admin/delete/{id}
    defaults:
        _controller: APAPlatformBundle:Admin:deleteUser
    requirements:
        id: \d+

apa_platform_editUser:
    path: /admin/edit/{id}
    defaults:
        _controller: APAPlatformBundle:Admin:editUser
    requirements:
        id: \d+

apa_platform_listUser:
    path: /admin/listUser/{search}
    defaults:
        _controller: APAPlatformBundle:Admin:dynamicSearch

# PARTIE USER

apa_platform_userIndex:
    path: /user
    defaults:
        _controller: APAPlatformBundle:User:userIndex

apa_platform_userFichiers:
    path: /user/Fichiers/{category}
    defaults:
        _controller: APAPlatformBundle:User:userFichiers

apa_platform_staff:
    path: /staff
    defaults:
        _controller: APAPlatformBundle:User:staff

apa_platform_userFiche:
    path: /user/MaFiche
    defaults:
        _controller: APAPlatformBundle:User:userFiche

apa_platform_settings:
    path: /user/settings
    defaults:
        _controller: APAPlatformBundle:User:settings

# PARTIE DOC

apa_platform_docIndex:
    path: /doc
    defaults:
        _controller: APAPlatformBundle:Doc:docIndex

