apa_platform_adminIndex:
    path: /admin
    defaults:
        _controller: APAPlatformBundle:Admin:adminIndex

apa_platform_adminListe:
    path: /admin/liste
    defaults:
        _controller: APAPlatformBundle:Admin:adminListe

apa_platform_addUser:
    path: /admin/addUser
    defaults:
        _controller: APAPlatformBundle:Admin:addUser

apa_platform_deleteUser:
    path: /admin/delete/{id}
    defaults:
        _controller: APAPlatformBundle:Admin:deleteUser
    requirements:
        id: \d+

apa_platform_editUser:
    path: /admin/edit/{id}
    defaults:
        _controller: APAPlatformBundle:Admin:editUser
    requirements:
        id: \d+

apa_platform_listUser:
    path: /admin/listUser/{search}
    defaults:
        _controller: APAPlatformBundle:Admin:dynamicSearch

apa_platform_userIndex:
    path: /user
    defaults:
        _controller: APAPlatformBundle:User:userIndex
